#--------------------------- Filestream input ----------------------------
filebeat.inputs:
- type: filestream
  enabled: true
  id: Magento 2 logs
  paths:
    - MAGENTO_WEB_ROOT_PATH/var/log/system.log

  parsers:
    - multiline:
        pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9].+\+[0-9]{2}:[0-9]{2}\]'
        negate: true
        match: after

  processors:
    - drop_event:
        when:
          regexp:
            message: 'main.INFO:'
    - dissect:
        tokenizer: '[%{date}] main.%{severity}: '
        field: "message"
        target_prefix: ""
    - dissect:
        tokenizer: '/home/%{owner}/'
        field: "log.file.path"
        target_prefix: ""
    - timestamp:
        field: date
        layouts:
          - '2006-01-02T15:04:05.000000+00:00'
        test:
          - '2022-11-25T18:24:05.000000+00:00'
    - drop_fields:
        fields: ["date"]

setup.template:
  name: "magento_logs"
  pattern: "magento_logs-%{[owner]}-%{[agent.version]}-*"
  overwrite: true
  enabled: false

setup.ilm.enabled: false

output.elasticsearch:
  hosts: ['http://127.0.0.1:9200']
  username: "magento_logs"
  password: "MAGENTO_LOGS_PASSWORD"
  index: 'magento_logs-%{[owner]}-%{[agent.version]}-%{+YYYY.MM.dd}'
  
