#--------------------------- Filestream input ----------------------------
filebeat.inputs:
- type: filestream
  enabled: true
  id: Magento 2 logs
  paths:
    - MAGENTO_WEB_ROOT_PATH/var/log/system.log
    #- /home/staging/public_html/var/log/system.log

  parsers:
    - multiline:
        pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9].+\+[0-9]{2}:[0-9]{2}\]'
        negate: true
        match: after

  processors:
    - drop_event:
        when:
          regexp:
            message: 'main.INFO:'
    - dissect:
        tokenizer: '[%{date}] main.%{severity}: %{error}'
        field: "message"
        target_prefix: ""
    - dissect:
        tokenizer: '/home/%{magento_owner}/'
        field: "source"
        target_prefix: "" 
    - timestamp:
        field: date
        timezone: 'MAGENTO_TIMEZONE'
        layouts:
          - '2022-06-22T16:33:51Z'
          - '2022-11-18T04:59:51.123Z'
          - '2022-08-03T07:10:20.123456+00:00'
        test:
          - '2022-06-22T16:33:51Z'
          - '2022-11-18T04:59:51.123Z'
          - '2022-08-03T07:10:20.123456+00:00'
    - drop_fields:
        fields: ["date","beat.name"]

setup.template:
  name: "magento_logs"
  pattern: "magento_logs-%{magento_owner}-%{[agent.version]}-*"
  overwrite: true
  enabled: false

setup.ilm.enabled: false

output.elasticsearch:
  hosts: ['http://127.0.0.1:9200']
  username: "magento_logs"
  password: "MAGENTO_LOGS_PASSWORD"
  index: 'magento_logs-%{magento_owner}-%{[agent.version]}-%{+YYYY.MM.dd}'
  
